version: '3'
services:

  web:
    container_name: web
    image: rkdwlals/coinvillage-web
    expose:
      - 3333
    ports:
      - 3333:3333

  nginx:
    container_name: nginx
    image: rkdwlals/coinvillage-nginx
    ports:
      - 80:80
    depends_on:
      - web